### ISSUE TITLE
[obd.commands] OBD commands can only be retrieved... 

### ISSUE THREAD

**Issue by agagliardi7** [brendanwhitfield/piHud#8]
Hi all,

I followed all the steps reported into the readme but I have some issue like below:

[obd.commands] OBD commands can only be retrieved by PID value or dict name
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/__main__.py", line 81, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/__main__.py", line 37, in main
    global_config = GlobalConfig(config_path)
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/GlobalConfig.py", line 27, in init
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/GlobalConfig.py", line 86, in load
    config = self.make_config(obd.commands[sensor])
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/GlobalConfig.py", line 31, in make_config
    config = default_for(command)
  File "/usr/local/lib/python2.7/dist-packages/pihud-0.1.0-py2.7.egg/pihud/defaults.py", line 70, in default_for
    config["sensor"] = command.name
AttributeError: 'NoneType' object has no attribute 'name'

I changed "python -m piHud" with "python -m pihud" otherwise no modue "piHud" is found, and second I do not have a ELM327 connected to the RPi (but I don't think that this is an issue).

Could you please help me to solve the problem? 
Thanks in advance.

**Comment by DeMuu** [comment]
I've got the same issue even if I'm connected to an adapter.

Using python-OBD on it's own in a simple script does work and returns values. Does anyone have tips on how to efficiently debug this?

**Comment by goof1112** [comment]
Its to do with the pihud.rc config file in the home/pi directory. Looks like that is created from the default.rc file however it doesnt like the sensor fields being in quotation marks. I dont really know enough about JSON to understand what its problem is but if you change the lines "sensor": "RPM", to "sensor": RPM,  in the pihud.rc the program should load.

I am unable to save any widget layouts becuase when its loading the terminal outputs:
Invalid json in config:
No JSON object could be decoded

However it continues to load the program.
I have been trying to work out what that means
Thanks
